version: 0.1.0-alpha.{build}
environment:
  CODECOV_TOKEN:
    secure: 7NwrC2/LQuGJujoTjelIGViuqX1kXSEuuJh3ZP5WKAMC93tBNp7AmUo18KBCcRLO
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true
branches:
  only:
  - master
  - /v\d+\.\d+/
before_build:
- ps: $env:versionSuffix = if ($env:APPVEYOR_PULL_REQUEST_NUMBER) { "pr$env:APPVEYOR_PULL_REQUEST_NUMBER.$env:APPVEYOR_BUILD_ID" } else { "$env:APPVEYOR_BUILD_ID" }
- ps: dotnet tool install -g dotnet-calcver
- ps: $env:customnugetversion = dotnet calcver version "$env:APPVEYOR_BUILD_FOLDER" "$env:versionSuffix"
- ps: Update-AppveyorBuild -Version $env:customnugetversion
- choco install opencover.portable
- choco install codecov
before_deploy:
  - ps: dotnet calcver log --destination "$env:APPVEYOR_BUILD_FOLDER\changelog.md" --format markdown
  - ps: cat "$env:APPVEYOR_BUILD_FOLDER\changelog.md"
  - ps: ${env:release_description} = (Get-Content -LiteralPath "$env:APPVEYOR_BUILD_FOLDER\changelog.md" -Encoding UTF8) -join "`n";
build_script:
- ps: dotnet pack -c release /p:PackageVersion=$env:customnugetversion
test_script:
- cmd: OpenCover.Console.exe -register:user -oldstyle -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test -c debug --logger:trx;LogFileName=results.trx /p:DebugType=full tests/P3.Konsole.Tests" -filter:"+[P3.Konsole*]* -[P3.Konsole.Tests*]*" -output:".\coverage.xml"
- cmd: codecov -f .\coverage.xml -t "%CODECOV_TOKEN%"

artifacts:
- path: src\**\release\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: cdk1PHxgO0eToAllOUT1sqZdSDsjcOTTR2tNX9ro5+WwnFVIhPv/hUifBEzs4A2Q
  skip_symbols: true
  on:
    appveyor_repo_tag: true
    appveyor_repo_tag_name: /\d+\.\d+.\d+(-[a-zA-Z0-9]+)?/
- provider: NuGet
  server: https://ci.appveyor.com/nuget/sanisoclem-1hsskq6nn06g
  api_key:
    secure: ovRAAP+pCt2eBZ5OoCKJaGh4vQbTUAZ8wnbsogY3sYw=
  skip_symbols: true
  on:
    branch: master
    appveyor_repo_tag: false
- provider: GitHub
  description: $(release_description)
  auth_token:
    secure: 8q1/CSBx/+8Qt6PJF/C+Pb+oevfM8haQ7qiRyEZ41UFUUGhSjs1QFNDUZGt0Hs3a
  artifact: /.*\.nupkg/
  draft: true
  on:
    appveyor_repo_tag: true
    appveyor_repo_tag_name: /\d+\.\d+.\d+(-[a-zA-Z0-9]+)?/