version: 0.1.0-alpha.{build}
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
init: #APPVEYOR_BUILD_ID
- ps: $env:customnugetversion = if ($env:APPVEYOR_REPO_TAG -eq $True) { "$env:APPVEYOR_REPO_TAG_NAME" } else { "$env:APPVEYOR_BUILD_VERSION" }
- ps: Update-AppveyorBuild -Version $env:customnugetversion
build_script:
- ps: dotnet pack -c release /p:PackageVersion=$env:customnugetversion
test_script:
- cmd: dotnet test tests/P3.Konsole.Tests
artifacts:
- path: src\**\release\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: cdk1PHxgO0eToAllOUT1sqZdSDsjcOTTR2tNX9ro5+WwnFVIhPv/hUifBEzs4A2Q
  skip_symbols: true
  on:
    appveyor_repo_tag: true
    appveyor_repo_tag_name: /\d+\.\d+.\d+(-[a-zA-Z0-9]+)?/
- provider: NuGet
  server: https://ci.appveyor.com/nuget/sanisoclem-1hsskq6nn06g
  api_key:
    secure: ovRAAP+pCt2eBZ5OoCKJaGh4vQbTUAZ8wnbsogY3sYw=
  skip_symbols: true
  on:
    branch: master
    appveyor_repo_tag: false